export const verbs = [
  { english: "to eat", german: "essen", example: "Ich esse einen Apfel." },
  { english: "to drink", german: "trinken", example: "Ich trinke Wasser." },
  { english: "to go", german: "gehen", example: "Ich gehe zur Schule." },
  { english: "to come", german: "kommen", example: "Er kommt nach Hause." },
  { english: "to see", german: "sehen", example: "Wir sehen einen Film." },
  { english: "to read", german: "lesen", example: "Sie liest ein Buch." },
  {
    english: "to write",
    german: "schreiben",
    example: "Ich schreibe einen Brief.",
  },
  { english: "to sleep", german: "schlafen", example: "Er schläft früh." },
  { english: "to run", german: "laufen", example: "Wir laufen im Park." },
  {
    english: "to walk",
    german: "spazieren",
    example: "Sie spaziert am Fluss.",
  },
  { english: "to speak", german: "sprechen", example: "Ich spreche Deutsch." },
  { english: "to listen", german: "hören", example: "Er hört Musik." },
  { english: "to play", german: "spielen", example: "Wir spielen Fußball." },
  { english: "to work", german: "arbeiten", example: "Sie arbeitet im Büro." },
  {
    english: "to cook",
    german: "kochen",
    example: "Ich koche das Abendessen.",
  },
  { english: "to learn", german: "lernen", example: "Wir lernen Deutsch." },
  {
    english: "to study",
    german: "studieren",
    example: "Sie studiert Medizin.",
  },
  { english: "to drive", german: "fahren", example: "Ich fahre ein Auto." },
  { english: "to buy", german: "kaufen", example: "Er kauft Obst." },
  { english: "to sell", german: "verkaufen", example: "Sie verkauft Blumen." },
  { english: "to open", german: "öffnen", example: "Ich öffne die Tür." },
  {
    english: "to close",
    german: "schließen",
    example: "Er schließt das Fenster.",
  },
  { english: "to sit", german: "sitzen", example: "Wir sitzen auf dem Stuhl." },
  { english: "to stand", german: "stehen", example: "Sie steht neben mir." },
  { english: "to wait", german: "warten", example: "Ich warte auf den Bus." },
  { english: "to buy", german: "kaufen", example: "Er kauft Brot." },
  {
    english: "to sell",
    german: "verkaufen",
    example: "Sie verkauft Kleidung.",
  },
  { english: "to need", german: "brauchen", example: "Ich brauche Hilfe." },
  { english: "to like", german: "mögen", example: "Wir mögen Eis." },
  { english: "to love", german: "lieben", example: "Er liebt seine Familie." },
  { english: "to hate", german: "hassen", example: "Ich hasse Lügen." },
  { english: "to know", german: "wissen", example: "Ich weiß die Antwort." },
  {
    english: "to understand",
    german: "verstehen",
    example: "Sie versteht Deutsch.",
  },
  {
    english: "to remember",
    german: "erinnern",
    example: "Ich erinnere mich an dich.",
  },
  {
    english: "to forget",
    german: "vergessen",
    example: "Er vergisst oft Termine.",
  },
  { english: "to help", german: "helfen", example: "Ich helfe dir." },
  { english: "to ask", german: "fragen", example: "Sie fragt nach dem Weg." },
  {
    english: "to answer",
    german: "antworten",
    example: "Er antwortet schnell.",
  },
  { english: "to call", german: "rufen", example: "Ich rufe meinen Freund." },
  { english: "to love", german: "lieben", example: "Wir lieben Musik." },
  {
    english: "to travel",
    german: "reisen",
    example: "Ich reise nach Deutschland.",
  },
  { english: "to swim", german: "schwimmen", example: "Wir schwimmen im See." },
  { english: "to fly", german: "fliegen", example: "Er fliegt nach Berlin." },
  { english: "to bring", german: "bringen", example: "Sie bringt Kuchen." },
  { english: "to take", german: "nehmen", example: "Ich nehme den Bus." },
  { english: "to wear", german: "tragen", example: "Er trägt eine Jacke." },
  {
    english: "to meet",
    german: "treffen",
    example: "Wir treffen unsere Freunde.",
  },
  { english: "to sing", german: "singen", example: "Ich singe ein Lied." },
  { english: "to dance", german: "tanzen", example: "Sie tanzt gern." },
  { english: "to draw", german: "zeichnen", example: "Ich zeichne ein Bild." },
  { english: "to paint", german: "malen", example: "Er malt ein Haus." },
  {
    english: "to fix",
    german: "reparieren",
    example: "Ich repariere das Fahrrad.",
  },
  { english: "to clean", german: "putzen", example: "Wir putzen das Zimmer." },
  { english: "to wash", german: "waschen", example: "Sie wäscht das Auto." },
  {
    english: "to brush",
    german: "bürsten",
    example: "Ich bürste meine Haare.",
  },
  { english: "to cut", german: "schneiden", example: "Er schneidet das Brot." },
  { english: "to open", german: "öffnen", example: "Ich öffne das Buch." },
  {
    english: "to close",
    german: "schließen",
    example: "Wir schließen das Fenster.",
  },
  { english: "to laugh", german: "lachen", example: "Sie lacht laut." },
  { english: "to cry", german: "weinen", example: "Er weint oft." },
  { english: "to smile", german: "lächeln", example: "Ich lächle dich an." },
  { english: "to show", german: "zeigen", example: "Wir zeigen unsere Fotos." },
  {
    english: "to hide",
    german: "verstecken",
    example: "Er versteckt das Geschenk.",
  },
  {
    english: "to sell",
    german: "verkaufen",
    example: "Ich verkaufe mein Auto.",
  },
  { english: "to buy", german: "kaufen", example: "Sie kauft ein Haus." },
  { english: "to open", german: "öffnen", example: "Wir öffnen das Geschäft." },
  { english: "to close", german: "schließen", example: "Er schließt das Tor." },
  { english: "to try", german: "versuchen", example: "Ich versuche es." },
  { english: "to win", german: "gewinnen", example: "Wir gewinnen das Spiel." },
  { english: "to lose", german: "verlieren", example: "Sie verliert oft." },
  { english: "to build", german: "bauen", example: "Er baut ein Haus." },
  { english: "to break", german: "brechen", example: "Ich breche das Brot." },
  { english: "to choose", german: "wählen", example: "Wir wählen das Beste." },
  {
    english: "to pay",
    german: "bezahlen",
    example: "Sie bezahlt die Rechnung.",
  },
  {
    english: "to sell",
    german: "verkaufen",
    example: "Er verkauft sein Auto.",
  },
  {
    english: "to send",
    german: "schicken",
    example: "Ich schicke eine Nachricht.",
  },
  { english: "to receive", german: "bekommen", example: "Wir bekommen Post." },
  {
    english: "to meet",
    german: "treffen",
    example: "Sie trifft ihre Freundin.",
  },
  { english: "to call", german: "anrufen", example: "Er ruft mich an." },
  { english: "to travel", german: "reisen", example: "Ich reise oft." },
  { english: "to stay", german: "bleiben", example: "Wir bleiben zu Hause." },
  { english: "to watch", german: "sehen", example: "Sie sieht einen Film." },
  { english: "to listen", german: "zuhören", example: "Ich höre dir zu." },
  { english: "to help", german: "helfen", example: "Wir helfen den Kindern." },
  { english: "to love", german: "lieben", example: "Er liebt Schokolade." },
  { english: "to like", german: "mögen", example: "Ich mag Kaffee." },
  { english: "to need", german: "brauchen", example: "Wir brauchen Wasser." },
  {
    english: "to understand",
    german: "verstehen",
    example: "Sie versteht die Aufgabe.",
  },
  { english: "to know", german: "kennen", example: "Ich kenne ihn gut." },
  { english: "to find", german: "finden", example: "Wir finden den Weg." },
  {
    english: "to lose",
    german: "verlieren",
    example: "Er verliert oft seine Schlüssel.",
  },
  {
    english: "to remember",
    german: "erinnern",
    example: "Ich erinnere mich an dich.",
  },
  {
    english: "to forget",
    german: "vergessen",
    example: "Sie vergisst die Hausaufgaben.",
  },
  {
    english: "to teach",
    german: "unterrichten",
    example: "Er unterrichtet Mathe.",
  },
  { english: "to learn", german: "lernen", example: "Ich lerne Deutsch." },
  {
    english: "to ask",
    german: "fragen",
    example: "Wir fragen nach dem Preis.",
  },
  {
    english: "to answer",
    german: "antworten",
    example: "Sie antwortet freundlich.",
  },
  {
    english: "to try",
    german: "versuchen",
    example: "Ich versuche das Rezept.",
  },
  {
    english: "to change",
    german: "ändern",
    example: "Er ändert seine Meinung.",
  },
  { english: "to wait", german: "warten", example: "Wir warten auf dich." },
  { english: "to open", german: "öffnen", example: "Sie öffnet die Tür." },
  {
    english: "to close",
    german: "schließen",
    example: "Ich schließe das Fenster.",
  },
  {
    english: "to start",
    german: "beginnen",
    example: "Wir beginnen das Spiel.",
  },
  {
    english: "to finish",
    german: "beenden",
    example: "Er beendet die Arbeit.",
  },
  { english: "to call", german: "rufen", example: "Ich rufe laut." },
  { english: "to clean", german: "putzen", example: "Wir putzen das Haus." },
  {
    english: "to fix",
    german: "reparieren",
    example: "Sie repariert den Stuhl.",
  },
  { english: "to play", german: "spielen", example: "Er spielt Gitarre." },
  { english: "to run", german: "rennen", example: "Ich renne schnell." },
  { english: "to walk", german: "gehen", example: "Wir gehen zusammen." },
];
